{% set name = "poetry-dynamic-versioning" %}
{% set version = "1.8.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: d14de13d426ac28e98f4519aac7f4aa857e7b97ad9d7a4c72293377033065f44

build:
  number: 0
  entry_points:
    - poetry-dynamic-versioning = poetry_dynamic_versioning.__main__:main
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv
  skip: true  # [py<37]

requirements:
  host:
    - pip
    - poetry-core 1.5.1
    - python
    - setuptools
    - wheel
  run:
    - dunamai >=1.17.0,<2.0.0
    - jinja2 >=2.11.1,<4
    - python
    - tomlkit >=0.4
  run_constrained:
    - poetry >=1.2.0,<2

test:
  imports:
    - poetry_dynamic_versioning
  requires:
    - pip
  commands:
    - pip check
    - poetry-dynamic-versioning --help

about:
  home: https://github.com/mtkennerly/poetry-dynamic-versioning
  dev_url: https://github.com/mtkennerly/poetry-dynamic-versioning
  doc_url: https://github.com/mtkennerly/poetry-dynamic-versioning
  summary: Plugin for Poetry to enable dynamic versioning based on VCS tags
  description: Plugin for Poetry to enable dynamic versioning based on VCS tags
  license: MIT
  license_family: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - dhirschfeld
    - BastianZim
