{% set name = "poetry-dynamic-versioning" %}
{% set version = "0.17.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 304eec793e8b71e3646b365671464c935626781e92dc029e35b01e8fe8c7530c

build:
  number: 0
  noarch: python
  entry_points:
    - poetry-dynamic-versioning = poetry_dynamic_versioning.__main__:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - poetry-core >=1.0.0
    - python >=3.6
  run:
    - dunamai >=1.12.0,<2.0.0
    - jinja2 >=2.11.1,<4
    - python >=3.6
    - tomlkit >=0.4

test:
  imports:
    - poetry_dynamic_versioning
  commands:
    - pip check
    - poetry-dynamic-versioning --help
  requires:
    - pip

about:
  home: https://github.com/mtkennerly/poetry-dynamic-versioning
  summary: Plugin for Poetry to enable dynamic versioning based on VCS tags
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - BastianZim
