{% set name = "poetry-dynamic-versioning" %}
{% set version = "1.9.1" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: d6e7b9df817aa2ca4946cd695c6c89e1379d2e6c640f008a9b6170d081a9da48

build:
  number: 0
  entry_points:
    - poetry-dynamic-versioning = poetry_dynamic_versioning.__main__:main
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv
  skip: true  # [py<37]

requirements:
  host:
    - pip
    - python
    - setuptools
    - wheel
    - poetry-core >=1.0.0
  run:
    - python
    - dunamai >=1.25.0,<2
    - tomlkit >=0.4
    - jinja2 >=2.11.1,<4
  run_constrained:
    - poetry >=1.2.0,<2

test:
  imports:
    - poetry_dynamic_versioning
  commands:
    - pip check
    - poetry-dynamic-versioning --help
  requires:
    - pip

about:
  home: https://github.com/mtkennerly/poetry-dynamic-versioning
  dev_url: https://github.com/mtkennerly/poetry-dynamic-versioning
  doc_url: https://github.com/mtkennerly/poetry-dynamic-versioning
  summary: Plugin for Poetry to enable dynamic versioning based on VCS tags
  description: Plugin for Poetry to enable dynamic versioning based on VCS tags
  license: MIT
  license_family: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - dhirschfeld
    - BastianZim
