{% set name = "poetry-dynamic-versioning" %}
{% set version = "1.10.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 52bf9ed57f2d60f4250a1dfe43db7b8144541df2f3ae6e712d12b43ecda71f47

build:
  number: 0
  entry_points:
    - poetry-dynamic-versioning = poetry_dynamic_versioning.__main__:main
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv
  skip: true  # [py<37]

requirements:
  host:
    - pip
    - python
    - setuptools
    - wheel
    - poetry-core >=1.0.0
  run:
    - python
    - dunamai >=1.26.0,<2
    - tomlkit >=0.4
    - jinja2 >=2.11.1,<4
  run_constrained:
    - poetry >=1.2.0,<2

# skip below tests due to the AssertionError
{% set skip_tests = " --deselect=tests/test_unit.py::test__enable_in_doc__project_with_version" %}
{% set skip_tests = skip_tests + " --deselect=tests/test_unit.py::test__enable_in_doc__project_with_dynamic" %}

{% set skip_file = "" %}
# skip below tests due to poetry support dropped in Python 3.12+ 
# for windows: No such file or directory: 'C:\\Users\\task_178774196301242\\croot\\poetry-dynamic-versioning_1787742055216\\_test_env\\Lib\\site-packages\\installer\\_scripts\\t64.exe' 
{% set skip_file = skip_file + " --ignore=tests/test_integration.py" %}  # [py>311 or win]

test:
  imports:
    - poetry_dynamic_versioning
  source_files:
    - tests
    # the lower specified files are required in test env
    - pyproject.toml
    - poetry_dynamic_versioning
    - README.md
  requires:
    - pytest >=7.0,<8.0
    - pip
    # poetry support dropped in Python 3.12+
    - poetry >=1.2.0  # [py<312]
    - git
  commands:
    - pip check
    - poetry-dynamic-versioning --help
    - git init && git config user.name "build_test_usr" && git config user.email "test@build.local" && git add . && git commit -m "test_commit"  # tests required an initialized git repository with dummy commit
    - pytest -ra -vv {{ skip_tests }} {{ skip_file }} tests

about:
  home: https://github.com/mtkennerly/poetry-dynamic-versioning
  dev_url: https://github.com/mtkennerly/poetry-dynamic-versioning
  doc_url: https://github.com/mtkennerly/poetry-dynamic-versioning
  summary: Plugin for Poetry to enable dynamic versioning based on VCS tags
  description: Plugin for Poetry to enable dynamic versioning based on VCS tags
  license: MIT
  license_family: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - dhirschfeld
    - BastianZim
